### PR TITLE
app_creation.md: Small restructuring, fix page-internal links, typos, QA

### PR DESCRIPTION
**Pull request by fritzbacke**
toc

### CODE REVIEW

**Comment by frikky** [comment]
Ooh, thanks - and especially for generalizing a lot of the information. I'll read through properly and test, then merge it in.

**Comment by fritzbacke** [comment]
I was also thinking to specify the default place for app documentation. Would that be an .md file in Shuffle-apps/Docs?

**Comment by frikky** [comment]
> I was also thinking to specify the default place for app documentation. Would that be an .md file in Shuffle-apps/Docs?

Yes, right now it's there, but we'll be moving all apps (OpenAPI & Python) to the shuffle-apps folder, then all keeping all documentation in the same location as the app itself. E.g:

shuffle-apps/thehive/1.0.0/docs.md

This way, we can use it on the frontend in an easier way as well

**Comment by fritzbacke** [comment]
ok, I added a description of that already to this pull request

**Comment by frikky** [comment]
Finally got time to look through again; thanks @fritzbacke!

**Pull request merged**
